<a href="https://colab.research.google.com/github/Kimhansav/introofnlp_practice/blob/main/_14_02(Word_Level_%EB%B2%88%EC%97%AD%EA%B8%B0_%EB%A7%8C%EB%93%A4%EA%B8%B0(Neural_Machine_Translation_(seq2seq)_Tutorial))practice_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
import re
import shutil
import zipfile

import numpy as np
import pandas as pd
import tensorflow as tf
import unicodedata
import urllib3
from tensorflow.keras.layers import Embedding, GRU, Dense
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
import requests

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

def download_zip(url, output_path):
    response = requests.get(url, headers=headers, stream=True)
    if response.status_code == 200:
        with open(output_path, 'wb') as f:
            for chunk in response.iter_content(chunk_size=8192):
                f.write(chunk)
        print(f"ZIP file downloaded to {output_path}")
    else:
        print(f"Failed to download. HTTP Response Code: {response.status_code}")

url = "http://www.manythings.org/anki/fra-eng.zip"
output_path = "fra-eng.zip"
download_zip(url, output_path)

path = os.getcwd()
zipfilename = os.path.join(path, output_path)

with zipfile.ZipFile(zipfilename, 'r') as zip_ref:
    zip_ref.extractall(path)

ZIP file downloaded to fra-eng.zip


In [ ]:
num_samples = 33000

In [ ]:
def to_ascii(s):
  #프랑스어 악센트(accent) 삭제
  #예시: 'déjà diné' -> deja dine
  return ''.join(c for c in unicodedata.normalize('NFD', s) if unicodedata.category(c) != 'Mn')

def preprocess_sentence(sent):
  #악센트 제거 함수 호출
  sent = to_ascii(sent.lower())

  #단어와 구두점 사이에 공백 추가.
  # ex) "I am a student." => "I am a student ."
  sent = re.sub(r"([?.!,¿])", r" \1", sent)

  #(a-z, A-Z, ".", "?", "!", ",") 이들을 제외하고는 전부 공백으로 변환
  sent = re.sub(r"[^a-zA-Z!.?]+", r" ", sent)

  #다수 개의 공백을 하나의 공백으로 치환
  sent = re.sub(r"\s+", " ", sent)
  return sent

In [ ]:
#전처리 테스트
en_sent = u"Have you had dinner?"
fr_sent = u"Avez-vous déjà diné?"

print('전처리 전 영어 문장 :', en_sent)
print('전처리 후 영어 문장 :',preprocess_sentence(en_sent))
print('전처리 전 프랑스어 문장 :', fr_sent)
print('전처리 후 프랑스어 문장 :', preprocess_sentence(fr_sent))

전처리 전 영어 문장 : Have you had dinner?
전처리 후 영어 문장 : have you had dinner ?
전처리 전 프랑스어 문장 : Avez-vous déjà diné?
전처리 후 프랑스어 문장 : avez vous deja dine ?


In [ ]:
def load_preprocessed_data():
  encoder_input, decoder_input, decoder_target = [], [], []

  with open("fra.txt", "r") as lines:
    for i, line in enumerate(lines):
      #source 데이터와 target 데이터 분리
      src_line, tar_line, _ = line.strip().split('\t')

      #source 데이터 전처리
      src_line = [w for w in preprocess_sentence(src_line).split()]

      #target 데이터 전처리
      tar_line = preprocess_sentence(tar_line)
      tar_line_in = [w for w in ("<sos> " + tar_line).split()]
      tar_line_out = [w for w in (tar_line + " <eos>").split()]

      encoder_input.append(src_line)
      decoder_input.append(tar_line_in)
      decoder_target.append(tar_line_out)

      if i == num_samples - 1:
        break
  return encoder_input, decoder_input, decoder_target

In [ ]:
sents_en_in, sents_fra_in, sents_fra_out = load_preprocessed_data()
print('인코더의 입력 :',sents_en_in[:5])
print('디코더의 입력 :',sents_fra_in[:5])
print('디코더의 레이블 :',sents_fra_out[:5])

인코더의 입력 : [['go', '.'], ['go', '.'], ['go', '.'], ['go', '.'], ['hi', '.']]
디코더의 입력 : [['<sos>', 'va', '!'], ['<sos>', 'marche', '.'], ['<sos>', 'en', 'route', '!'], ['<sos>', 'bouge', '!'], ['<sos>', 'salut', '!']]
디코더의 레이블 : [['va', '!', '<eos>'], ['marche', '.', '<eos>'], ['en', 'route', '!', '<eos>'], ['bouge', '!', '<eos>'], ['salut', '!', '<eos>']]


In [ ]:
tokenizer_en = Tokenizer(filters = "", lower = False)
tokenizer_en.fit_on_texts(sents_en_in)
encoder_input = tokenizer_en.texts_to_sequences(sents_en_in)
encoder_input = pad_sequences(encoder_input, padding = 'post')

tokenizer_fra = Tokenizer(filters = "", lower = False)
tokenizer_fra.fit_on_texts(sents_fra_in)
tokenizer_fra.fit_on_texts(sents_fra_out)

decoder_input = tokenizer_fra.texts_to_sequences(sents_fra_in)
decoder_input = pad_sequences(decoder_input, padding = "post")

decoder_target = tokenizer_fra.texts_to_sequences(sents_fra_out)
decoder_target = pad_sequences(decoder_target, padding = "post")

In [ ]:
print('인코더의 입력의 크기(shape) :',encoder_input.shape)
print('디코더의 입력의 크기(shape) :',decoder_input.shape)
print('디코더의 레이블의 크기(shape) :',decoder_target.shape)

인코더의 입력의 크기(shape) : (33000, 7)
디코더의 입력의 크기(shape) : (33000, 16)
디코더의 레이블의 크기(shape) : (33000, 16)


In [ ]:
src_vocab_size = len(tokenizer_en.word_index) + 1
tar_vocab_size = len(tokenizer_fra.word_index) + 1
print("영어 단어 집합의 크기 : {:d}, 프랑스어 단어 집합의 크기 : {:d}".format(src_vocab_size, tar_vocab_size))

영어 단어 집합의 크기 : 4487, 프랑스어 단어 집합의 크기 : 7883


In [ ]:
src_to_index = tokenizer_en.word_index
index_to_src = tokenizer_en.index_word
tar_to_index = tokenizer_fra.word_index
index_to_tar = tokenizer_fra.index_word

In [ ]:
indices = np.arange(encoder_input.shape[0])
np.random.shuffle(indices)
print('랜덤 시퀀스 :',indices)

랜덤 시퀀스 : [20715  4613  5630 ...  3208 11239 20067]


In [ ]:
encoder_input = encoder_input[indices]
decoder_input = decoder_input[indices]
decoder_target = decoder_target[indices]

In [ ]:
encoder_input[30997]

array([  29, 3373,  134,    1,    0,    0,    0], dtype=int32)

In [ ]:
decoder_input[30997]

array([   2,   12,   16,   93,  314, 5433,    1,    0,    0,    0,    0,
          0,    0,    0,    0,    0], dtype=int32)

In [ ]:
decoder_target[30997]

array([  12,   16,   93,  314, 5433,    1,    3,    0,    0,    0,    0,
          0,    0,    0,    0,    0], dtype=int32)

In [ ]:
n_of_val = int(33000 * 0.1)
print('검증 데이터의 개수 :',n_of_val)

검증 데이터의 개수 : 3300


In [ ]:
encoder_input_train = encoder_input[:-n_of_val]
decoder_input_train = decoder_input[:-n_of_val]
decoder_target_train = decoder_target[:-n_of_val]

encoder_input_test = encoder_input[-n_of_val:]
decoder_input_test = decoder_input[-n_of_val:]
decoder_target_test = decoder_target[-n_of_val:]

In [ ]:
print('훈련 source 데이터의 크기 :',encoder_input_train.shape)
print('훈련 target 데이터의 크기 :',decoder_input_train.shape)
print('훈련 target 레이블의 크기 :',decoder_target_train.shape)
print('테스트 source 데이터의 크기 :',encoder_input_test.shape)
print('테스트 target 데이터의 크기 :',decoder_input_test.shape)
print('테스트 target 레이블의 크기 :',decoder_target_test.shape)

훈련 source 데이터의 크기 : (29700, 7)
훈련 target 데이터의 크기 : (29700, 16)
훈련 target 레이블의 크기 : (29700, 16)
테스트 source 데이터의 크기 : (3300, 7)
테스트 target 데이터의 크기 : (3300, 16)
테스트 target 레이블의 크기 : (3300, 16)


In [ ]:
from tensorflow.keras.layers import Input, LSTM, Embedding, Dense, Masking
from tensorflow.keras.models import Model

In [ ]:
embedding_dim = 64
hidden_units = 64

In [ ]:
#인코더
encoder_inputs = Input(shape = (None,))
enc_emb = Embedding(src_vocab_size, embedding_dim)(encoder_inputs) #임베딩층
enc_masking = Masking(mask_value = 0.0)(enc_emb) #패딩 0은 연산에서 제외
encoder_lstm = LSTM(hidden_units, return_state = True) #상태값 리턴을 위해 return_states는 True
encoder_outputs, state_h, state_c = encoder_lstm(enc_masking) #은닉 상태와 셀 상태를 리턴
encoder_states = [state_h, state_c] #인코더의 은닉 상태와 셀 상태를 저장

In [ ]:
#디코더
decoder_inputs = Input(shape = (None,))
dec_emb_layer = Embedding(tar_vocab_size, hidden_units) #임베딩층
dec_emb = dec_emb_layer(decoder_inputs) #패딩 0은 연산에서 제외
dec_masking = Masking(mask_value = 0.0)(dec_emb)

#상태값 리턴을 위해 return_state는 True, 모든 시점에 대해서 단어를 예측하기 위해 return_sequences는 True
decoder_lstm = LSTM(hidden_units, return_sequences = True, return_state = True)

#인코더의 은닉 상태를 초기 은닉 상태(initial_state)로 사용
decoder_outputs, _, _ = decoder_lstm(dec_masking, initial_state = encoder_states)

#모든 시점의 결과에 대해서 소프트맥스 함수를 사용한 출력층을 통해 단어 예측
decoder_dense = Dense(tar_vocab_size, activation = 'softmax')
decoder_outputs = decoder_dense(decoder_outputs)

#모델의 입력과 출력을 정의
model = Model([encoder_inputs, decoder_inputs], decoder_outputs)

model.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['acc'])

In [ ]:
model.fit(x = [encoder_input_train, decoder_input_train], y = decoder_target_train, validation_data = ([encoder_input_test, decoder_input_test], decoder_target_test), batch_size = 128, epochs = 50)

Epoch 1/50
233/233 [==============================] - 33s 85ms/step - loss: 3.3637 - acc: 0.6176 - val_loss: 2.0564 - val_acc: 0.6213
Epoch 2/50
233/233 [==============================] - 8s 35ms/step - loss: 1.8875 - acc: 0.6467 - val_loss: 1.7769 - val_acc: 0.7079
Epoch 3/50
233/233 [==============================] - 7s 30ms/step - loss: 1.6793 - acc: 0.7382 - val_loss: 1.6124 - val_acc: 0.7515
Epoch 4/50
233/233 [==============================] - 7s 31ms/step - loss: 1.5463 - acc: 0.7547 - val_loss: 1.5065 - val_acc: 0.7615
Epoch 5/50
233/233 [==============================] - 7s 31ms/step - loss: 1.4408 - acc: 0.7641 - val_loss: 1.4212 - val_acc: 0.7668
Epoch 6/50
233/233 [==============================] - 7s 32ms/step - loss: 1.3580 - acc: 0.7752 - val_loss: 1.3535 - val_acc: 0.7798
Epoch 7/50
233/233 [==============================] - 7s 30ms/step - loss: 1.2891 - acc: 0.7855 - val_loss: 1.2930 - val_acc: 0.7905
Epoch 8/50
233/233 [==============================] - 7s 30ms/step -

In [ ]:
#인코더
encoder_model = Model(encoder_inputs, encoder_states)

#디코더 설계 시작
#이전 시점의 상태를 보관할 텐서
decoder_state_input_h = Input(shape = (hidden_units,))
decoder_state_input_c = Input(shape = (hidden_units,))
decoder_states_inputs = [decoder_state_input_h, decoder_state_input_c]

#훈련 때 사용했던 임베딩 층을 재사용
dec_emb2 = dec_emb_layer(decoder_inputs)

#다음 단어 예측을 위해 이전 시점의 상태를 현 시점의 초기 상태로 사용
decoder_outputs2, state_h2, state_c2 = decoder_lstm(dec_emb2, initial_state = decoder_states_inputs)
decoder_states2 = [state_h2, state_c2]

#모든 시점에 대해서 단어 예측
decoder_outputs2 = decoder_dense(decoder_outputs2)

#수정된 디코더
decoder_model = Model(
    [decoder_inputs] + decoder_states_inputs,
    [decoder_outputs2] + decoder_states2
)

In [ ]:
def decode_sequence(input_seq):
  #입력으로부터 인코더의 마지막 시점의 상태(은닉 상태, 셀 상태)를 얻음
  states_value = encoder_model.predict(input_seq)

  #<SOS>에 해당하는 정수 생성
  target_seq = np.zeros((1,1))
  target_seq[0,0] = tar_to_index['<sos>']

  stop_condition = True
  decoded_sentence = ''

  #stop_condition이 True가 될 때까지 루프 반복
  #구현의 간소화를 위해서 이 함수는 배치 크기를 1로 가정합니다.
  while not stop_condition:
    #이전 시점의 상태 states_value를 현 시점의 초기 상태로 사용
    output_tokens, h, c = decoder_model.predict([target_seq] + states_value)

    #예측 결과를 단어로 변환
    sampled_token_index = np.argmax(output_tokens[0, -1, :])
    sampled_char = index_to_tar[sampled_token_index]

    #현재 시점의 예측 단어를 예측 문장에 추가
    decoded_sentence += ' '+sampled_char

    #<eos>에 도달하거나 정해진 길이를 넘으면 중단.
    if (sampled_char == '<eos>' or len(decoded_sentence) > 50):
      stop_condition = True

    #현재 시점의 예측 결과를 다음 시점의 입력으로 사용하기 위해 저장
    target_seq = np.zeros((1,1))
    target_seq[0,0] = sampled_token_index

    #현재 시점의 상태를 다음 시점의 상태로 사용하기 위해 저장
    states_value = [h, c]

  return decoded_sentence

In [ ]:
#원문의 정수 시퀀스를 텍스트 시퀀스로 변환
def seq_to_src(input_seq):
  sentence = ''
  for encoded_word in input_seq:
    if (encoded_word != 0):
      sentence = sentence + index_to_src[encoded_word] + ' '
  return sentence

#번역문의 정수 시퀀스를 텍스트 시퀀스로 변환
def seq_to_tar(input_seq):
  sentence = ''
  for encoded_word in input_seq:
    if(encoded_word != 0 and encoded_word != tar_to_index['<sos>'] and encoded_word != tar_to_index['<eos>']):
      sentence = sentence + index_to_tar[encoded_word] + ' '
  return sentence

In [ ]:
for seq_index in [3, 50, 100, 300, 1001]:
  input_seq = encoder_input_train[seq_index : seq_index + 1]
  decoded_sentence = decode_sequence(input_seq)

  print("입력문장 :",seq_to_src(encoder_input_train[seq_index]))
  print("정답문장 :",seq_to_tar(decoder_input_train[seq_index]))
  print("번역문장 :",decoded_sentence[1:-5])
  print("-"*50)

1/1 [==============================] - 0s 18ms/step
입력문장 : the music stopped . 
정답문장 : la musique s est arretee . 
번역문장 : 
--------------------------------------------------
1/1 [==============================] - 0s 16ms/step
입력문장 : what is your name ? 
정답문장 : comment est ce que tu t appelles ? 
번역문장 : 
--------------------------------------------------
1/1 [==============================] - 0s 16ms/step
입력문장 : give me that . 
정답문장 : donnez moi ca . 
번역문장 : 
--------------------------------------------------
1/1 [==============================] - 0s 17ms/step
입력문장 : rake the leaves . 
정답문장 : ratissez les feuilles . 
번역문장 : 
--------------------------------------------------
1/1 [==============================] - 0s 17ms/step
입력문장 : can i pay later ? 
정답문장 : puis je payer plus tard ? 
번역문장 : 
--------------------------------------------------


In [ ]:
for seq_index in [3, 50, 100, 300, 1001]:
  input_seq = encoder_input_test[seq_index : seq_index + 1]
  decoded_sentence = decode_sequence(input_seq)

  print("입력문장 :",seq_to_src(encoder_input_test[seq_index]))
  print("정답문장 :",seq_to_tar(decoder_input_test[seq_index]))
  print("번역문장 :",decoded_sentence[1:-5])
  print("-"*50)

1/1 [==============================] - 0s 17ms/step
입력문장 : he cried for joy . 
정답문장 : il a pleure de joie . 
번역문장 : 
--------------------------------------------------
1/1 [==============================] - 0s 16ms/step
입력문장 : thank you . 
정답문장 : merci . 
번역문장 : 
--------------------------------------------------
1/1 [==============================] - 0s 16ms/step
입력문장 : take it easy ! 
정답문장 : on se calme ! 
번역문장 : 
--------------------------------------------------
1/1 [==============================] - 0s 17ms/step
입력문장 : is her story true ? 
정답문장 : son histoire est elle vraie ? 
번역문장 : 
--------------------------------------------------
1/1 [==============================] - 0s 16ms/step
입력문장 : i sat at the bar . 
정답문장 : je me suis assis au bar . 
번역문장 : 
--------------------------------------------------
